runtime: python39

handlers:
- url: /Assets
  static_dir: Assets 

- url: /(.*) 
  static_files: \1
  upload: (.*)

- url: /
  static_files: index.html
  upload: index.html

- url: /.*
  static_files: index.html
  upload: index.html
